# Generated by Django 4.2.3 on 2023-09-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('username', models.TextField()),
                ('userdiv', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
