# Generated by Django 4.2.3 on 2023-09-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateduser',
            name='userID',
        ),
    ]
