# Generated by Django 4.2.3 on 2023-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_rateduser_options_alter_rateduser_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateduser',
            options={'verbose_name': 'RatedUser', 'verbose_name_plural': 'RatedUser'},
        ),
        migrations.AddField(
            model_name='rateduser',
            name='userrating',
            field=models.IntegerField(default=0, verbose_name='레이팅'),
            preserve_default=False,
        ),
    ]
