# Generated by Django 4.2.3 on 2023-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_rateduser_seasonstartrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateduser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='핸들'),
        ),
    ]
